[package]
name = "gemini"
version = "0.1.0"
authors = ["NiVeK92 <Ztear@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.22.0"
simba = { version = "0.2", default-features = false }